### ISSUE TITLE
Extension not loading in electron.

### ISSUE THREAD

**Issue by vedangdate** [mobxjs/mobx-devtools#11]
I tried to install the extension by adding the following code in my electron.js file's create window function -

`const installExtension = require('electron-devtools-installer')
  installExtension
    .default('pfgnfdagidkfgccljigdamigbcnndkod')
    .then(name => console.log(`Added Extension:  ${name}`))
    .catch(err => console.log('An error occurred: ', err))`

The tab mobx is visible but is stuck on 'connecting...'. Even though the extension is running smoothly for the same app served as web app. That is to say it runs on the browser but not in the electron.

**Comment by aap82** [comment]
Same issue as well when trying to install using this method:

` BrowserWindow.addDevToolsExtension(
    "/path/to/chrome/extensions/pfgnfdagidkfgccljigdamigbcnndkod/0.9.8_0"
  )`

**Comment by andykog** [comment]
Electron doesn't trigger [onConnect](https://github.com/andykog/mobx-devtools/blob/8ef66d4/src/shells/webextension/background.js#L155) in the background page after [connect](https://github.com/andykog/mobx-devtools/blob/8ef66d4/src/shells/webextension/panel.jsx#L32). No idea why, trying to figure that out.

**Comment by natew** [comment]
Woah just ran into this and see it was commented on 2 hours ago :) 👍

**Comment by andykog** [comment]
Turned out, that electron doesn't support some webextension API's.
Fixed in v0.9.9

**Comment by natew** [comment]
Thanks for the quick patch here.

I am trying to use [chrome-extension-downloader](https://github.com/jiripospisil/chrome-ext-downloader) and it downloads 0.9.8 still:

```
npm i -g chrome-extension-downloader
ced pfgnfdagidkfgccljigdamigbcnndkod
```

Is this published?

**Comment by andykog** [comment]
Yep, the latest version in chrome web store is 0.9.9 right now: https://chrome.google.com/webstore/detail/mobx-developer-tools/pfgnfdagidkfgccljigdamigbcnndkod?hl=en

`ced pfgnfdagidkfgccljigdamigbcnndkod` downloads v0.9.9 for me

**Comment by vedangdate** [comment]
Sorry for the late acknowledgement. And Thanks a lot!

**Comment by renarsvilnis** [comment]
Hi, I'm having trouble having the plugin find MobX (using MST), it's stuck at "Looking for mobx...".
Can you help me?

<img width="233" alt="screen shot 2017-12-06 at 19 32 40" src="https://user-images.githubusercontent.com/3515099/33675731-3ede0ae4-dabc-11e7-93a5-aad63170aa5e.png">


I'm using: 

```json
{
  "electron": "1.7.9",
  "mobx": "3.3.3",
  "mobx-devtools-mst": "0.9.9",
  "mobx-react": "4.3.5",
  "mobx-state-tree": "1.2.1"
}
```

Do I need to do anything else to make the plugin work with MST besides the code below?

```javascript
import makeInspectable from 'mobx-devtools-mst';

import Store from 'modules/Store';

const store = makeInspectable(Store.create({}));
```

**Comment by andykog** [comment]
@renarsvilnis, you haven't given the version of the chrome extension. What method are you using to install it? If that's `electron-devtools-installer`, you could check the version in `userDataFolder/extensions/pfgnfdagidkfgccljigdamigbcnndkod/manifest.json`
To find out `userDataFolder` addres paste this in your electron app:
```js
// main.js
import electron, { remote } from 'electron';
console.log((remote || electron).app.getPath('userData'))
```

**Comment by andykog** [comment]
@realityforge, I'm sure you have installed quite old version. The up-to-date one should have blue logo, not red :-)

**Comment by renarsvilnis** [comment]
@andykog Thanks for the fast reply. You are totally right. I'm both using `electron-devtools-installer` and also the extension version is `0.0.17`. Force downloaded latest versions, now it works! 🎉  Thanks, @andykog!

**Comment by 2A5F** [comment]
This bug also exists in xx 0.9.21_0

**Comment by aceslowman** [comment]
Also experiencing this with 0.9.22, stuck with ‘connecting’. Running it in electron, which is using create-react-app and mobx. Could this be related to hot-reloading somehow? 

Update:
I have been able to get the standalone mobx-devtools working in lieu of the extension, so if others are running into this problem, that should work in a pinch. 

Install globally:
`npm i -g mobx-devtools`

Add script to index.html:
`<script src="//localhost:8098"></script>`

**Comment by hadnet** [comment]
@aceslowman your solution unfortunately didn't work. I'm using Electron 12.05 and and mobx-devtools 0.9.26. I also tried with electron-devtools-installer but doesn't work either, still stuck "connecting'.

**Comment by chemzqm** [comment]
Same issue on Electron 12.0.0 and latest mobx-devtools0.9.26,  stuck on "connecting'.

**Comment by BasixKOR** [comment]
I'm using electron-devtools-installer as well and using Devtool 0.9.26 but it keeps showing 'connecting'. It seems like inject has been called (considering global hook had registered collection thing), but it has no listeners attached, which means backend must be not initialized properly.

**Comment by benglewis** [comment]
I am still stuck on "Connecting" on MobX DevTools v0.9.26
