### ISSUE TITLE
"Undefined" value when profiling

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-devtools#13]
Hi there,

First of all, thank you for sharing the devtools. 

I'm trying this with a sample app build with `react-create-app` and noticed that when I'm profiling my components I get an `undefined` string as in the image below: 

<img width="342" alt="2017-11-26_0109" src="https://user-images.githubusercontent.com/1224078/33241754-55ea366a-d2c2-11e7-899c-9181547fde07.png">

Any suggestions on what this may be? 

Thanks in advance,

Carlos

**Comment by andykog** [comment]
@carlosagsmendes, strange this app https://react-mobx.realworld.io/ ([source](https://github.com/gothinkster/react-mobx-realworld-example-app)) is also based on `react-create-app`, but has no such problem. Can you provide the following info?
* What versions of `mobx`, `mobx-react` are you using?
* How do you define `MyComponent`? (class/function? decorators?)
* What do you get when select `MyComponent` in ”Components" tab and then execute `$m.render.$mobx.name` in browser console?

**Comment by carlosagsmendes** [comment]
Hi @andykog,

- What versions of mobx, mobx-react are you using?
mobx 3.3.2 mobx-react 4.3.5  react 16.1.1

- How do you define MyComponent? (class/function? decorators?)
I reported the error using a class. 

Switching to a function doesn't work. I even tried setting the component name explicitly - as suggested on Mobx documentation - and shown below, but it gets worse with `"_class#undefined.render()"` being displayed.  

`// 1 (set displayName explicitly)
export const MyComponent = observer((props => <div>hi</div>))
myComponent.displayName = "MyComponent"`
 

- What do you get when select MyComponent in ”Components" tab and then execute $m.render.$mobx.name in browser console?

"MyComponent#undefined.render()" (when defining the component as a class)

I can try to create a repro online if that may help.

Thanks

**Comment by andykog** [comment]
@carlosagsmendes, thanks, created a PR in https://github.com/mobxjs/mobx-react/pull/368

**Comment by carlosagsmendes** [comment]
Thank you for the support!
