### ISSUE TITLE
FEATURE: Action name in log

### ISSUE THREAD

**Issue by PawelGIX** [mobxjs/mobx-devtools#15]
Hello, Could actions show their names in log?

![image](https://user-images.githubusercontent.com/391153/34253623-ad546ada-e648-11e7-9449-62735b493629.png)

![image](https://user-images.githubusercontent.com/391153/34311219-a2ba8702-e75c-11e7-99f1-344e177004de.png)

**Comment by torkelo** [comment]
I am not seeing any action names either (using mobx-state-tree), not even when I expand. 

![image](https://user-images.githubusercontent.com/10999/34815921-828ff988-f6b3-11e7-9824-5467a9f8415e.png)

**Comment by andykog** [comment]
Thanks for reporting, actions' names should be visible (v0.9.12)
