### ISSUE TITLE
No performance tab

### ISSUE THREAD

**Issue by janat08** [mobxjs/mobx-devtools#17]
I see no performance tab

**Comment by andykog** [comment]
what version of mobx-react are you using? Is it 4.2.2+?

**Comment by janat08** [comment]
None, I thought it was for profiling mobx itself.

**Comment by andykog** [comment]
Currently it only works when mobx-react is available, I'll add a note about that to README.md

**Comment by janat08** [comment]
Tried just adding it to fail.

**Comment by andykog** [comment]
What version? Have you imported it in some fie?

**Comment by janat08** [comment]
lol I just cdn it into index html, I have no clue if it was actually in scope :D.

**Comment by janat08** [comment]
So then I just added
<script src="https://unpkg.com/mobx-react"></script>
as per instructions, on npm readme. I take it you don't actually have to
use the package in your project?

**Comment by janat08** [comment]
like I don't use react either.
