### ISSUE TITLE
Idea: move repo to Mobx org for more visibility

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-devtools#20]
This tool is really cool, and it is used quite a lot, but doesn't get the attention it deserves yet. Moving it to the mobx org might increase visibility:)

**Comment by andykog** [comment]
Done!

**Comment by mweststrate** [comment]
Awesome, thanks!

Op wo 7 feb. 2018 om 12:40 schreef Andy Kogut <notifications@github.com>:
