### ISSUE TITLE
Tested with MobX 4.x?

### ISSUE THREAD

**Issue by nitelite** [mobxjs/mobx-devtools#22]
When I upgraded to MobX 4 it looks like the Dev Tools stopped detecting MobX on the page? Could this be the case or did I mess something up when upgrading?

**Comment by jantimon** [comment]
I got a similar behaviour.
After a reload the devtool freezes most of the time:
![screen](https://user-images.githubusercontent.com/4113649/37449376-48ddc0e6-282a-11e8-96b8-d02524423ff3.jpg)

**Comment by andykog** [comment]
@nitelite, @jantimon, seems that this problem is related to #23. v0.9.13 should work fine, can you confirm?
