### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by marvinhagemeister** [mobxjs/mobx-devtools#23]
Love this extension, has been a huge productivity boost for us.

We have one issue though, where the extension fails to initialise due to missing `undefined` check. This is fixed in master for a few weeks now and we would really appreciate a new release 🎉 

For reference, this is the error:

<img width="787" alt="screen shot 2018-03-13 at 15 43 56" src="https://user-images.githubusercontent.com/1062408/37348843-618740be-26d5-11e8-943d-30d110966c84.png">

**Comment by andykog** [comment]
Sorry for the delay, published as 0.9.13

**Comment by marvinhagemeister** [comment]
@andykog Awesome, thank you so much 🎉
