### ISSUE TITLE
 All components are named "Object" 

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-devtools#39]
Hi, any idea why all components are named "Object"? 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/2682705/46518543-15cb9000-c8b8-11e8-95df-f2c63d1a32f6.png">

Thanks for the WONDERFUL tool!

**Comment by Amareis** [comment]
I think it's related to react-hot-loader, because if you reload page (so components is surely not hot-reloaded), you will see it's original names.

**Comment by andykog** [comment]
@tomitrescak, is it indeed related to react-hot-loader?

**Comment by tomitrescak** [comment]
@andykog nope, I just switched to create-react-app without the hot loader and it is the same. It says Object on initial page load ;(

**Comment by evisong** [comment]
I met the same issue, the weird thing is, when I switch the tabs back and forth, the `<Object>` duplicates itself:

![jan-06-2019 16-35-02](https://user-images.githubusercontent.com/651208/50733925-349c3400-11d1-11e9-9a79-5662edc5cb7a.gif)

My Mobx versions:

- mobx@4.6.0
- mobx-devtools-mst@0.9.18
- mobx-react@5.4.2
- mobx-state-tree@3.8.1
- MobX Developer Tools: 0.9.20

**Comment by shidianxia** [comment]
@evisong me too

**Comment by austinfox** [comment]
I'm experiencing this same issue (All components are being labeled "Object"). I am hot-loading components as well.

**Comment by XGHeaven** [comment]
Anything update? same error for me.

**Comment by epodgaetskiy** [comment]
Hi!
Prefer use React Devtools extension for components tree and performance [discuss](https://github.com/mobxjs/mobx-devtools/issues/56#issuecomment-541896923)
