### ISSUE TITLE
Displayed elements gets cut off.

### ISSUE THREAD

**Issue by Glinkis** [mobxjs/mobx-devtools#42]
When trying to view the devtools in chrome, everything just cuts off after a short bit.
<img width="262" alt="screenshot 2018-12-11 at 09 27 07" src="https://user-images.githubusercontent.com/8037927/49787484-24567d80-fd27-11e8-8925-5fcf296f1d16.png">

**Comment by andykog** [comment]
Cannot reproduce, what versions of mobx-devtools extension & Chrome are you using?

**Comment by vladlavrik** [comment]
I am facing a similar problem (no tabs `Components` and `Performance`)
Reproduced when using `mobx-react-lite` or `mobx-react@6`. With `mobx-react@5` works okay.
  
Chrome version: 75.0.3770.100
Extension version: latest

<img width="579" alt="img" src="https://user-images.githubusercontent.com/10566567/59962315-69384980-94ec-11e9-883f-49848e6df07e.png">

**Comment by paxarpp** [comment]
> When trying to view the devtools in chrome, everything just cuts off after a short bit.
> <img alt="screenshot 2018-12-11 at 09 27 07" width="262" src="https://user-images.githubusercontent.com/8037927/49787484-24567d80-fd27-11e8-8925-5fcf296f1d16.png">

Hi,
The same problem for a year already, always the latest versions,
presently :
Chrome 86.0.4240.198
Extension version: latest

**Comment by epodgaetskiy** [comment]
@vladlavrik Hi!
Prefer use React Devtools extension for components tree and performance [discuss](https://github.com/mobxjs/mobx-devtools/issues/56#issuecomment-541896923). The new version of mobx-devtools doesn't have Components and Performance tabs.
