### ISSUE TITLE
Undo makeInspectable

### ISSUE THREAD

**Issue by Ridermansb** [mobxjs/mobx-devtools#48]
My app create one store per page component.. `constructor` of each page componente will execute `MyPageXStore.create({})`

But after open the page again (the component will be create again) the tab is created again..

![screen shot 2019-02-25 at 22 06 07](https://user-images.githubusercontent.com/725337/53379764-a4b17580-3949-11e9-9b07-d502d74668e2.png)

How can I remove the tab when component unmounted?

**Comment by andykog** [comment]
Destroyed MST roots should be removed automatically in the next version
