### ISSUE TITLE
Performance tab not visible on mobx-react 6.1.1

### ISSUE THREAD

**Issue by deanvanniekerk** [mobxjs/mobx-devtools#56]
I think there might be an issue with the latest version of mobx and mobx-react.
If i have the below installed I dont see the performance and components tabs
```
"mobx": "5.10.1",
"mobx-react": "6.1.1",
```
<img width="273" alt="Screen Shot 2019-06-27 at 09 19 36" src="https://user-images.githubusercontent.com/3798908/60245344-b3d70e80-98bc-11e9-8b84-85a256b89386.png">

but if i downgrade to 
```
"mobx": "3.6.2",
"mobx-react": "4.4.3",
```

then all works fine.

<img width="350" alt="Screen Shot 2019-06-27 at 09 13 25" src="https://user-images.githubusercontent.com/3798908/60245179-5216a480-98bc-11e9-9d5e-a109bc4793d3.png">

Thank for the great plugin by the way 👍

**Comment by deanvanniekerk** [comment]
To be more specific with the versions. I lose the tabs when going from `mobx-react 5.4.4 -> 6.0.0`

If it helps im using typescript, this is my config
```
{
    "compilerOptions": {
        "strictNullChecks": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "noEmit": true,
        "target": "esnext",
        "allowJs": true,
        "jsx": "react",
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"]
        },
        "typeRoots": ["node_modules/@types", "typings"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": ["./src/"]
}
```

**Comment by Tsury** [comment]
I just see the Changes tab, using 
```
"mobx": "5.10.1",
"mobx-react": "6.1.1",
"mobx-react-devtools": "6.1.1",
```
Using standalone version.

How can I also see the Components tab?

**Comment by blinkcat** [comment]
only changes tab, using
>    "mobx": "^4.12.0",
    "mobx-react": "^6.1.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",

**Comment by FrederickIge** [comment]
same issue here

**Comment by ghost** [comment]
me too.

**Comment by ibovegar** [comment]
Using firefox plugin. Same issue as well.

**Comment by bichotll** [comment]
Same here.

**Comment by alexalv** [comment]
Same here, using
> "mobx": "^5.13.0",
> "mobx-react": "^6.1.3",

**Comment by damienallen** [comment]
Same problem with FF, Chrome and the standalone version.

```
{
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.3",
}
```

**Comment by nulldef** [comment]
Same problem here

**Comment by williamoliveira** [comment]
Is anyone working on a fix for this or is this project dead?

**Comment by anikethsaha** [comment]
I am trying to fix it. Hope to submit the ASAP.

**Comment by williamoliveira** [comment]
@anikethsaha is it a complex fix? has much changed?

**Comment by anikethsaha** [comment]
I guess no, updating a few methods.  But getting other errors so just fixing those.
I have a fix ready for it but it will break other things. 😄

**Comment by danielkcz** [comment]
From mobx-react 6 changelog ... I can believe nobody here actually read it 😆 

![image](https://user-images.githubusercontent.com/1096340/66394160-9e51a480-e9d4-11e9-93c4-748e80ac87da.png)

**Comment by anikethsaha** [comment]
Yea I actually forgot to comment about these . i had a look in the changelog and I already started without this. Sorry for not mentioning here. 
I was trying to port the devtool support for v6 but couldn't do it as it was not easy as I thought.

**Comment by williamoliveira** [comment]
@FredyC do you have some info on why it was killed?

**Comment by danielkcz** [comment]
I think @mweststrate can answer that better, but mostly I believe it was because there are better tools today (like React Devtools) so there is no point having another specific tool.

**Comment by mweststrate** [comment]
Correct, with React 16 the devtools can do exactly the same thing as we did
for performance measurements before. So all the code that was needed for
that (quite some) has been dropped from mobx-react, making the package
leaner instead.

**Comment by williamoliveira** [comment]
Ok, that covers re-rendering visualization, but what about visualizing what components reacts to and what actions are updating?

**Comment by danielkcz** [comment]
@williamoliveira See the last point in the picture I posted above or [original changelog with links](https://github.com/mobxjs/mobx-react/blob/master/CHANGELOG.md#600). I don't have personal experience with it, though. Strangely enough, I never had a need to investigate why is something re-rendering, it kinda made sense to me without any tool.

**Comment by Venryx** [comment]
Just wanted to mention that this is one of the first things I'll be looking to add to my fork here: https://github.com/Venryx/mobx-devtools-advanced

We'll see if I succeed in implementing it, but it's certainly something I'll try to add, as deep dependency tree viewing is something I really miss from my custom dependency tracking system I'd used prior to transitioning to MobX.

**Comment by Venryx** [comment]
Just got a *very primitive* implementation working for viewing the list of observables that an `@observer` component is watching:
![](https://i.imgur.com/9dleFY5.png)

I want to emphasize that the screenshot above is not at all representative of the final state, it's just a first demonstration that the pathway for displaying the information is in place. The full implementation will have expanding of component subtrees like before, arbitrarily-deep expansion of the dependency tree for each component, no need to manually press the "Refresh" button for things, much nicer layout and styling, etc.

That said, the basic functionality does work, so if someone urgently needs the functionality, they can clone my forked repo and install it locally: https://github.com/Venryx/mobx-devtools-advanced

Local install instructions (possibly incomplete): https://github.com/Venryx/mobx-devtools-advanced/blob/master/Docs/Hacking.md

**Comment by Venryx** [comment]
Updates:
* The extension now lets you view the "deep dependencies" of a component.
* The data-viewer UI uses an expandable tree. (rather than flat json display)

![](https://i.imgur.com/KlqPF7K.png)

I'll definitely work on this more, though progress may be sparse atm, since currently I'm only implementing the features I need to efficiently debug some issues in my main project.

Once I resolve those issues in my main project, I can revisit the extension to give it some much needed feature development and UI improvement.

**Comment by Venryx** [comment]
I've been making some more progress on my fork, but from now on I'll give updates on its development in this other issue: #55

**Comment by epodgaetskiy** [comment]
Hi!
Prefer use React Devtools extension for components tree and performance [discuss](https://github.com/mobxjs/mobx-devtools/issues/56#issuecomment-541896923)
