### ISSUE TITLE
Unable to vertically scroll in MST package

### ISSUE THREAD

**Issue by jdcookie** [mobxjs/mobx-devtools#59]
Chrome: Version 76.0.3809.132
Mac: 10.14.4

![image](https://user-images.githubusercontent.com/5629363/64583205-8423a700-d3d3-11e9-8e59-7ce51460499c.png)

Once the State on the right hand side goes beyond the vertical space, you cannot scroll.

This used to work, not sure what has stopped it from working.

**Comment by LiamDotPro** [comment]
This is also still happening for me, makes the dev tools a little unusable.

**Comment by pavan-shipmnts** [comment]
Right click on the MST object and click on store and global variable and then in the chrome/ff devtools console you can go through the MST store

**Comment by jarodhanko** [comment]
This is a css issue where the panel that displays the component tree does not have a maxHeight (and none of the parents do either.

I am not sure how to fix it properly, but if you pull the git repo and compile the extension after adding

maxHeight: '95vh' to src/frontend/TabComponents/index.jsx > styles.panelBody

It will allow scrolling again.  I haven't tested using MST, but it had the same issue for normal mobx in chrome. I also only tested in chrome.

**Comment by qinhuaihe** [comment]
@jarodhanko How to overwrite the installed `mobx-devtools`. I pasted my files into `mobx-devtools` extesion folder, and the extension became broken.

**Comment by jarodhanko** [comment]
@zmayor Here are the steps that I took

1. Clone the git repo
2. run npm install in both the root folder and in the each folder in packages 
3. update src/frontend/TabComponents/index.jsx > styles.panelBody to add maxHeight: '95vh'
4. run npm build:chrome which should generate a chrome.zip file which you need to extract somewhere
5. open chrome extensions page
6. toggle on developer mode.
7. open /lib/chrome (or whereever you extracted your zip file) and add a folder icons with some random png files icon-16.png, icon-48.png, icon-128.png, toolbar-chrome.png, toolbar-chrome@2x.png (apparently required by chrome for extensions to be loaded; I just renamed a random jpg file)
8. Disable the original extension
8. Click load unpacked on the chrome extensions page and point it to /lib/chrome or wherever your extracted folder is

**Comment by qinhuaihe** [comment]
Way to fix MST panel:
adding `maxHeight: '95vh'` to `src/frontend/TabMST/LogItemExplorer.jsx > styles.logExplorer`.

**Comment by epodgaetskiy** [comment]
Please upgrade to 0.9.26 version of mobx-devtools-mst.
