### ISSUE TITLE
types not found for mobx-devtools-mst

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mobx-devtools#67]
I'm attempting to use `mobx-devtools-mst` in typescript and I'm not seeing types. I tried to install `@types/mobx-devtools-mst` but I see types have been removed from that as it says that types are provided. I've got `0.9.21` installed and don't see any types however.

**Comment by pluma** [comment]
Same. Problem is that the `@types/mobx-devtools-mst` package is a stub package claiming the library ships its own types, which is not (or no longer) true.

**Comment by SylvanasGone** [comment]
@chrisdrackett Try to downgrade to @types/mobx-devtools-mst@0.9.0(which hasn't been deprecated) as a temporary alternative. It worked for me.

**Comment by TotallWAR** [comment]
The same here. Do you have plans to support typescript typings?
