### ISSUE TITLE
[DOCUMENTATION] TypeError: mobxReact.trackComponents is not a function

### ISSUE THREAD

**Issue by d4rky-pl** [mobxjs/mobx-devtools#7]
Hey, seems that the latest version of this extension crashes on mobx-react 4.2.1 with the crash above. The application doesn't start and shows `TypeError: mobxReact.trackComponents is not a function`.

I was unable to reproduce this problem either on 4.1.8 or 4.2.2 so I believe it's a bug in mobx-react. It should be either documented in README or at least fail gracefully so other people won't spend that extra debugging time :)

**Comment by andykog** [comment]
Thanks for reporting, fixed in v0.9.4
