### ISSUE TITLE
Extension not loading in electron.

### ISSUE THREAD

**Issue by 2A5F** [mobxjs/mobx-devtools#71]
![TIM截图20200220175856](https://user-images.githubusercontent.com/13982338/74922927-eb299b00-540a-11ea-9f09-065e999b33a7.png)
![TIM截图20200220175925](https://user-images.githubusercontent.com/13982338/74922938-ecf35e80-540a-11ea-89a1-a6ad52e1000f.png)

**Comment by minaiism** [comment]
Same problem here... any ideas?

**Comment by minaiism** [comment]
@2A5F Did you solve the problem?

**Comment by hadnet** [comment]
Same thing here. I'm using 
```json
  "electron": "^12.0.5",
  "electron-devtools-installer": "^3.2.0",
```

 I tried installing mobx-devtools globally but didn't work wither.

**Comment by hadnet** [comment]
@2A5F did you solve the issue? Can you share with us?

**Comment by 2A5F** [comment]
@hadnet
I simply don't use it, react dev tool is enough for me
