### ISSUE TITLE
Module not found: Can't resolve 'mobx-state-tree'

### ISSUE THREAD

**Issue by kolnogorov** [mobxjs/mobx-devtools#74]
I have mobx 5.15.4 and my app does not live inside an iframe.
Here are my mobx-related depencencies:
```
    "mobx": "^5.15.4",
    "mobx-devtools-mst": "^0.9.22",
    "mobx-react": "^6.2.2",
```

When i try to import devtools like so: 
```
import makeInspectable from 'mobx-devtools-mst'
```
I get the following error:
```
Module not found: Can't resolve 'mobx-state-tree' in '/Users/kolnogorov/Projects/mobx-project/node_modules/mobx-devtools-mst/lib'
```

**Comment by alex9110** [comment]
I have the same problem. I just installed this package and everything is ok. 
yarn add mobx-state-tree

**Comment by epodgaetskiy** [comment]
Please upgrade to `0.9.26` version of `mobx-devtools-mst`.

**Comment by sibstark** [comment]
@epodgaetskiy Hello. I have the same issue with 0.9.30 version

    "mobx": "^6.1.7",
    "mobx-react": "^7.1.0",
    "mobx-devtools-mst": "^0.9.30"

p.s I downgraded mobx-devtools-mst on 0.9.26 and nothing changed

![Screenshot_177](https://user-images.githubusercontent.com/15224416/112607650-0657ad00-8e4c-11eb-82a4-42e9bdd8e524.png)

**Comment by Artem-Tsymbal** [comment]
@epodgaetskiy the same error 0.9.26

**Comment by devigor21** [comment]
Try `npm i mobx-state-tree`
It helped me
