### ISSUE TITLE
How to detect UI performance  with react native？Performance & Components tabs do not appear in Standalone app

### ISSUE THREAD

**Issue by luckysunle** [mobxjs/mobx-devtools#76]
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 17.53 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

here is the snapshoot:
<img width="801" alt="屏幕快照 2020-06-27 下午8 03 56" src="https://user-images.githubusercontent.com/15939437/85922004-d8403f00-b8b2-11ea-9b97-1fa47a9ea56d.png">

"dependencies": {
    "mobx": "4.9.2",
    "mobx-devtools": "^0.9.21",
    "mobx-devtools-mst": "^0.9.22",
    "mobx-react": "5.4.3",
    "mobx-react-devtools": "^6.1.1",
    "mobx-state-tree": "^3.16.0",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-gesture-handler": "1.2.0",
    "react-navigation": "3.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.10.3",
    "@babel/plugin-proposal-decorators": "^7.10.3",
    "@babel/runtime": "^7.10.3",
    "@types/react": "^16.9.41",
    "@types/react-native": "^0.62.13",
    "babel-jest": "^26.1.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "jest": "^26.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.8.3",
    "typescript": "^3.9.5"
  },

**Comment by epodgaetskiy** [comment]
Hi!
Prefer use React Devtools extension for components tree and performance [discuss](https://github.com/mobxjs/mobx-devtools/issues/56#issuecomment-541896923)
