### ISSUE TITLE
mobx-state-tree devtools typeScript error: export default (root: Root): Root => {};

### ISSUE THREAD

**Issue by wjureczka** [mobxjs/mobx-devtools#88]
Hey, after updating mobx-devtools all errors disappeared, but new ones came:
![obraz](https://user-images.githubusercontent.com/24592871/97321304-03419c00-186f-11eb-9aca-09d400462398.png)

Is anything that I can do about it?

**Comment by epodgaetskiy** [comment]
You can use version`0.9.22` of `mobx-devtools-mst`. We'll fix it in the next release. Thank you!

**Comment by wjureczka** [comment]
@epodgaetskiy  thanks for quick response, cheers!

**Comment by epodgaetskiy** [comment]
You can update to version `0.9.26` of mobx-devtools-mst. We fixed.
