### ISSUE TITLE
Mobx 0.9.8 not showing performance tab

### ISSUE THREAD

**Issue by ekeric13** [mobxjs/mobx-devtools#9]
All that is shown is changes.

<img width="336" alt="screen shot 2017-10-31 at 4 13 15 pm" src="https://user-images.githubusercontent.com/6489651/32253121-7d791dfc-be56-11e7-8878-c2f71a0f3da1.png">

**Comment by andykog** [comment]
@ekeric13, what version of mobx-react are you using? Is it 4.2.2+?
