### ISSUE TITLE
How to use mobx-devtools in ReactJS ??

### ISSUE THREAD

**Issue by flexboni** [mobxjs/mobx-devtools#98]
I am beginner of React.
So! Can you teach me how to use `mobx-devtools` in React??
If you have some examples, please tell me~^^

Thx

**Comment by cooljser** [comment]
@flexboni If you don't use mobx library, you can just use react-devtools chrome extension.

**Comment by AHillsie** [comment]
@flexboni If you close the issue there'd be one less.
